### ISSUE TITLE
Trapped in game

### ISSUE THREAD

**Issue by maxwofford** [hackclub/www-assemble#32]
After triggering the game easter egg, I can't get past this step b/c the button doesn't do anything (covered by #31)
<img width="959" alt="Screen Shot 2022-07-01 at 19 17 01" src="https://user-images.githubusercontent.com/5891442/176976899-fc066f75-3a8f-4ab4-9355-6f424a2979f9.png">
 
That's it's own bug, but this ticket is to track the game not resetting on refresh. Currently, if I reset the page, the page loads in as the screenshot above. I expect to be able to read the details of the event & apply, but I'm prevented from doing either.

**Comment by sampoder** [comment]
@Merlin04 any idea what could be causing this?

**Comment by Merlin04** [comment]
That was intentional, although I can see how that isn't really desired behavior. Right now, it serves the game with a service worker, and adds a key to indexeddb so shift reload won't work. If you comment out these lines: https://github.com/hackclub/www-assemble/blob/main/components/eat-ster-egg.js#L106

The indexeddb stuff will be disabled, so you can shift reload to reset. If you want regular reload to work you can make the page served by the worker automatically unregister the worker once it loads.
